# Generated by Django 4.1.3 on 2023-02-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_rating_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomments',
            name='text',
            field=models.TextField(max_length=1500),
        ),
    ]
