# Generated by Django 4.1.3 on 2023-02-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_productcomments_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomments',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
