# Generated by Django 4.1.3 on 2023-02-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_productcomments_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomments',
            name='title',
            field=models.CharField(default='What', max_length=250),
            preserve_default=False,
        ),
    ]
