# Generated by Django 4.1.3 on 2023-02-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_productcomments_productcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-02-08 17:26:46.975980 +00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-02-08 17:26:46.975980 +00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-02-08 17:26:46.975980 +00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
