# Generated by Django 4.1 on 2022-08-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerSpareParts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to='publisher-logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
