# Generated by Django 4.0.6 on 2022-08-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerSpareParts', '0003_alter_company_city_alter_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
