# Generated by Django 4.1 on 2022-08-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerSpareParts', '0004_alter_company_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='payments',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComputerSpareParts.paymenttype'),
        ),
    ]
