# Generated by Django 4.1 on 2022-08-30 14:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerSpareParts', '0005_paymenttype_alter_payments_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberofCores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AddField(
            model_name='сomputersparepart',
            name='cores',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ComputerSpareParts.numberofcores'),
            preserve_default=False,
        ),
    ]
