# Generated by Django 4.1 on 2022-08-30 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerSpareParts', '0006_numberofcores_сomputersparepart_cores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сomputersparepart',
            name='cores',
        ),
        migrations.AddField(
            model_name='сomputersparepart',
            name='numberofcores',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='NumberofCores',
        ),
    ]
