# Generated by Django 4.0.6 on 2022-08-31 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerSpareParts', '0007_remove_сomputersparepart_cores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сomputersparepart',
            old_name='numberofcores',
            new_name='сores',
        ),
        migrations.AddField(
            model_name='сomputersparepart',
            name='flow',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(256), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='сomputersparepart',
            name='ghz',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(8.429), django.core.validators.MinValueValidator(0)]),
        ),
    ]
