# Generated by Django 4.1 on 2022-09-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerSpareParts', '0009_comments_rename_cspimages_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersparepart',
            name='graphics_processing_unit',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='computersparepart',
            name='graphics_processing_unit_frequency',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='computersparepart',
            name='processor_series',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='computersparepart',
            name='video_memory_type',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
