# Generated by Django 4.1 on 2022-09-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerSpareParts', '0010_computersparepart_graphics_processing_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
