# Generated by Django 4.1 on 2022-09-18 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerSpareParts', '0011_alter_company_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='computersparepart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ComputerSpareParts.computersparepart'),
        ),
    ]
