# Generated by Django 4.1 on 2022-09-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerSpareParts', '0016_alter_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
