# Generated by Django 4.1 on 2022-10-13 11:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('logo', models.ImageField(null=True, upload_to='publisher-logo')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('cores', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(1)])),
                ('flow', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(256), django.core.validators.MinValueValidator(0)])),
                ('ghz', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(8.429), django.core.validators.MinValueValidator(0)])),
                ('count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv0.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('processor_series', models.CharField(max_length=300)),
                ('graphics_processing_unit', models.CharField(max_length=300)),
                ('graphics_processing_unit_frequency', models.CharField(max_length=300)),
                ('video_memory_type', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('from_date', models.DateField(auto_now=True)),
                ('to_date', models.DateField(auto_now=True)),
                ('computersparepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv0.computersparepart')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('computer_spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv0.computersparepart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('computer_spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv0.computersparepart')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv0.paymenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('computer_spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv0.computersparepart')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('computer_spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv0.computersparepart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='CSP-images')),
                ('computer_spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv0.computersparepart')),
            ],
        ),
        migrations.AddField(
            model_name='computersparepart',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv0.type'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=500)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('computer_spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv0.computersparepart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('computer_spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv0.computersparepart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
