from orders.tests.test_models.test_company import TestCompanyView
from orders.tests.test_models.test_category import TestCategoryView
from orders.tests.test_models.test_product import TestProductView
from orders.tests.test_models.test_product_comments import TestProductCommentsView
from orders.tests.test_models.test_product_images import TestProductImagesView
from orders.tests.test_models.test_product_rating import TestProductRatingView
from orders.tests.test_models.test_sub_category import TestSubCategoryView
