from orders.tests.test_views.test_category import TestCategoryAPIView
from orders.tests.test_views.test_company import TestCompanyAPIView
from orders.tests.test_views.test_product import TestProductAPIView
from orders.tests.test_views.test_sub_category import TestSubCategoryAPIView
